#!/bin/bash

echo "🔧 配置 Docker 使用 VPN 代理"
echo "================================"
echo ""
echo "检测到系统代理："
echo "  HTTP:  127.0.0.1:7897"
echo "  HTTPS: 127.0.0.1:7897"
echo ""
echo "请按照以下步骤配置 Docker Desktop："
echo ""
echo "1️⃣ 打开 Docker Desktop"
echo ""
echo "2️⃣ 点击右上角 ⚙️ 设置"
echo ""
echo "3️⃣ 选择 'Resources' → 'Proxies'"
echo ""
echo "4️⃣ 启用 'Manual proxy configuration'"
echo ""
echo "5️⃣ 填入以下信息："
echo "   Web Server (HTTP):  http://127.0.0.1:7897"
echo "   Secure Web Server (HTTPS): http://127.0.0.1:7897"
echo ""
echo "6️⃣ 点击 'Apply & Restart'"
echo ""
echo "7️⃣ 等待 Docker 重启（约 30 秒）"
echo ""
echo "================================"
echo ""
echo "配置完成后运行："
echo "  docker-compose -f docker-compose.cn.yml up -d --build"
echo ""
echo "或者直接运行原版："
echo "  docker-compose up -d --build"
